language: java
sudo: required
services:
  - docker
jdk:
- oraclejdk8
install:
- ./mvnw -B -q -Pdocker-gitlab dependency:go-offline verify -DskipTests -Ddocker.skip
script:
- ./mvnw -B -V -Pdocker-gitlab verify
